### ISSUE TITLE
Crash when trying to jump to address

### ISSUE THREAD

**Issue by Notselwyn** [ReClassNET/ReClass.NET#202]
I get an error about string formatting when trying to use the filter `[<AssaultCube.exe> + 0x10F4F4]`, according to the readme this should work. Anyone got a fix? I'm using Windows 10 build 19041.1083

full exception:
```
************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at ReClassNET.AddressParser.Tokenizer.TryReadNumberToken()
   at ReClassNET.AddressParser.Tokenizer.ReadNextToken()
   at ReClassNET.AddressParser.ExpressionParser.ParseAddSubtract()
   at ReClassNET.AddressParser.ExpressionParser.ParseLeaf()
   at ReClassNET.AddressParser.ExpressionParser.ParseMultiplyDivide()
   at ReClassNET.AddressParser.ExpressionParser.ParseAddSubtract()
   at ReClassNET.AddressParser.ExpressionParser.ParseExpression()
   at ReClassNET.AddressParser.ExpressionParser.Parse(String str)
   at ReClassNET.Memory.RemoteProcess.ParseAddress(String addressFormula)
   at ReClassNET.Nodes.ClassNode.UpdateAddress(RemoteProcess process)
   at ReClassNET.UI.MemoryViewControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at ReClassNET.UI.ScrollableCustomControl.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Notselwyn** [comment]
update: was trying x86 process on the x64 version because I'm blind... I'm sorry! Issue closed.
