### ISSUE TITLE
Inserting bytes throws an unhandled exception

### ISSUE THREAD

**Issue by qqshutup** [ReClassNET/ReClass.NET#254]
### Steps to reproduce
- Add a **union** at any offset
- Select the **union** and insert some byte

![Screenshot_1](https://user-images.githubusercontent.com/132127493/235289343-3f48db3a-fbe5-412b-96de-509b0bebb281.png)

### Exception Text
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: The index -1 is not in the range [0, 1].
   at ReClassNET.Nodes.BaseContainerNode.InsertBytes(Int32 index, Int32 size, List`1& createdNodes)
   at ReClassNET.Forms.MainForm.InsertBytesInClass(Int32 bytes)
   at ReClassNET.Forms.MainForm.insertBytesToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by KN4CK3R** [comment]
Thank you for the report. Fixed with [a895421](https://github.com/ReClassNET/ReClass.NET/commit/a895421d2e8aa20a02d25696ec305b09a7f37a6d).
