### ISSUE TITLE
i got this issue at ReClass.NET v1.1

### ISSUE THREAD

**Issue by nymphetm** [ReClassNET/ReClass.NET#57]
===================================

Method not found: 'System.__Canon System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr)'. (ReClass.NET)

------------------------------
For help, click: https://github.com/KN4CK3R/ReClass.NET/issues

------------------------------
Program Location:

   at ReClassNET.Core.NativeCoreWrapper.GetFunctionDelegate[TDelegate](IntPtr handle, String function)
   at ReClassNET.Core.NativeCoreWrapper..ctor(IntPtr handle)
   at ReClassNET.Core.InternalCoreFunctions..ctor(IntPtr handle)
   at ReClassNET.Core.CoreFunctionsManager..ctor()
   at ReClassNET.Program.Main()

**Comment by KN4CK3R** [comment]
I have never seen this error. Are you using Mono?
